tasks:
  - name: startup
    init: >
      pip install -r requirements.txt
      export FLASK_APP=run.py
      export FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

    

#     $ flask shell
# $ >>> from app import db
# $ >>> db.create_all()